# Generated by Django 4.1.3 on 2022-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_student_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
