# Generated by Django 4.1.3 on 2022-12-05 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, null=True)),
                ('document', models.TextField(null=True)),
                ('article', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
                ('category', models.CharField(blank=True, choices=[('부전공', '부전공'), ('복수전공', '복수전공')], max_length=10, null=True)),
                ('reference', models.CharField(default='multimajor', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('money', models.CharField(max_length=20, null=True)),
                ('reference', models.CharField(default='scholarship', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.TextField(null=True)),
                ('description', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='post/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('카페', '카페'), ('음식점', '음식점'), ('술집', '술집')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='facility/')),
                ('url', models.URLField(null=True)),
                ('reference', models.CharField(default='facility', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('음악', '음악'), ('여행', '여행'), ('공부', '공부'), ('종교', '종교'), ('운동', '운동'), ('사진', '사진'), ('문화생활', '문화생활'), ('소프트웨어', '소프트웨어')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='club/')),
                ('url', models.URLField(null=True)),
                ('reference', models.CharField(default='club', max_length=40, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
