# Generated by Django 4.1.3 on 2022-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('카페', '카페'), ('음식점', '음식점'), ('술집', '술집')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='database_project/dbapp/static/images/hanseo_logo.png', null=True, upload_to='')),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
