# Generated by Django 4.1.3 on 2022-11-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/hanseo_logo.png', null=True, upload_to=''),
        ),
    ]
