# Generated by Django 4.1.3 on 2022-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_alter_facility_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/hanseo_logo.png', null=True, upload_to='facility/'),
        ),
    ]
