# Generated by Django 4.1.3 on 2022-11-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_alter_facility_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('음악', '음악'), ('여행', '여행'), ('공부', '공부'), ('종교', '종교'), ('운동', '운동'), ('사진', '사진'), ('문화생활', '문화생활')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='/static/images/hanseo_logo.png', null=True, upload_to='club/')),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
