# Generated by Django 4.1.3 on 2022-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(blank=True, choices=[('음악', '음악'), ('여행', '여행'), ('공부', '공부'), ('종교', '종교'), ('운동', '운동'), ('사진', '사진'), ('문화생활', '문화생활'), ('소프트웨어', '소프트웨어')], max_length=50, null=True),
        ),
    ]
