# Generated by Django 4.1.3 on 2022-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_alter_club_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='phone_number',
            new_name='tel_number',
        ),
    ]
