# Generated by Django 4.1.3 on 2022-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_rename_phone_number_club_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='club/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='facility/'),
        ),
    ]
