# Generated by Django 4.1.3 on 2022-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_rename_phone_number_club_tel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, null=True)),
                ('document', models.TextField(null=True)),
                ('article', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
                ('category', models.CharField(blank=True, choices=[('부전공', '부전공'), ('복수전공', '복수전공')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('money', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
