# Generated by Django 4.1.3 on 2022-11-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0007_alter_club_image_alter_facility_image'),
        ('dbapp', '0007_multimajor_scholarship'),
    ]

    operations = [
    ]
