# Generated by Django 4.1.3 on 2022-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_merge_20221127_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='table',
            field=models.CharField(default='club', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='table',
            field=models.CharField(default='facility', max_length=50, null=True),
        ),
    ]
