# Generated by Django 4.1.3 on 2022-11-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_merge_20221127_1627'),
        ('dbapp', '0009_club_table_facility_table'),
    ]

    operations = [
    ]
