# Generated by Django 4.1.3 on 2022-11-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbapp', '0010_merge_20221127_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to=settings.AUTH_USER_MODEL),
        ),
    ]
