# Generated by Django 4.1.3 on 2022-11-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0015_alter_facility_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimajor',
            name='table',
            field=models.CharField(default='multimajor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='table',
            field=models.CharField(default='scholarship', max_length=50, null=True),
        ),
    ]
