# Generated by Django 4.1.3 on 2022-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0016_multimajor_table_scholarship_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='table',
            field=models.CharField(default='club', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='multimajor',
            name='table',
            field=models.CharField(default='multimajor', max_length=40, null=True),
        ),
    ]
