# Generated by Django 4.1.3 on 2022-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0017_alter_club_table_alter_multimajor_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='table',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='table',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='multimajor',
            old_name='table',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='table',
            new_name='reference',
        ),
    ]
