# Generated by Django 4.1.3 on 2022-11-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0017_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='hanseo_logo.png', null=True, upload_to='post/'),
        ),
    ]
