# Generated by Django 4.1.3 on 2022-11-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0018_rename_table_club_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='reference',
        ),
    ]
