# Generated by Django 4.1.3 on 2022-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0019_remove_scholarship_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='reference',
            field=models.CharField(default='scholarship', max_length=50, null=True),
        ),
    ]
