# Generated by Django 4.1.3 on 2022-11-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0020_scholarship_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='reference',
        ),
    ]
