# Generated by Django 4.1.3 on 2022-11-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0018_post_image'),
        ('dbapp', '0022_scholarship_reference'),
    ]

    operations = [
    ]
